export type EditCreateMenuType = "overview" | "edit" | "create"

export type EditCreateCategoryType = "edit" | "create"
export type EditCreateAccountType = "edit" | "create"

export type Menus =
  | "editCreateTransMenu"
  | "calendarMenu"
  | "chooseAccountMenu"
  | "chooseCategoryMenu"
  | "chooseCategorySlideMenu"
  | "dateMenu"
  | "nameMenu"
  | "passwordMenu"
  | "sideBar"
  | "titleMenu"
  | "signOutMenu"
  | "editCreateCurrencyMenu"
  | "currencyMenu"
  | "accountCurrencyMenu"
  | "editCreateCategoryMenu"
  | "categoryIconPickerMenu"
  | "editCreateAccountMenu"
  | "accountIconPickerMenu"
  | "languageMenu"
  | "themeMenu"
  | "currencyFormatMenu"
