export type EditCreateMenuType = "overview" | "edit" | "create"

export type EditCreateCategoryType = "edit" | "create"

export type Menus =
  "editCreateTransMenu"
  | "calendarMenu"
  | "chooseAccountMenu"
  | "chooseCategoryMenu"
  | "chooseCategorySlideMenu"
  | "dateMenu"
  | "nameMenu"
  | "passwordMenu"
  | "sideBar"
  | "titleMenu"
  | "signOutMenu"
  | "editCreateCurrencyMenu"
  | "currencyMenu"
  | "editCreateCategoryMenu"
  | "categoryIconPickerMenu"