export type DayType = "Sun" | "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat"


export const Days = new Map()
Days.set("Sun", 0)
Days.set("Mon", 1)
Days.set("Tue", 2)
Days.set("Wed", 3)
Days.set("Thu", 4)
Days.set("Fri", 5)
Days.set("Sat", 6)
Days.set(0, "Sun")
Days.set(1, "Mon")
Days.set(2, "Tue")
Days.set(3, "Wed")
Days.set(4, "Thu")
Days.set(5, "Fri")
Days.set(6, "Sat")

export const FullDays = new Map()
FullDays.set("Sunday", 0)
FullDays.set("Monday", 1)
FullDays.set("Tuesday", 2)
FullDays.set("Wednesday", 3)
FullDays.set("Thursday", 4)
FullDays.set("Friday", 5)
FullDays.set("Saturday", 6)
FullDays.set(0, "Sunday")
FullDays.set(1, "Monday")
FullDays.set(2, "Tuesday")
FullDays.set(3, "Wednesday")
FullDays.set(4, "Thursday")
FullDays.set(5, "Friday")
FullDays.set(6, "Saturday")