export const ApiError = {
  USER_EXIST: "User with this email already exist",
  USER_NOT_FOUND: "User was not found",
  ACCOUNT_NOT_FOUND: "Account was not found",
  ACCOUNT_EXIST: "This account is already exist",
  ACCOUNT_NOT_DELETED: "Could not delete the account",
  CATEGORY_EXIST: "This category is already exist",
  CATEGORY_NOT_FOUND: "Category was not found",
  CATEGORY_NOT_DELETED: "Could not delete the category",
  TRANSACTION_NOT_FOUND: "Transaction was not found",
  TRANSACTION_NOT_CREATED: "Could not create a transaction",
  TRANSACTION_NOT_EDITED: "Could not edit the transaction",
  TRANSACTION_NOT_DELETED: "Could not delete the transaction",
  WRONG_DATA: "Email or password is not correct",
  INVALID_CODE: "The code is invalid or expired",
  FILE_TYPE: "Avatar image type is invalid",
}
